### ISSUE TITLE
呵呵哒

### ISSUE THREAD

**Issue by WangGuibin** [smile-momoda/wx#1]
rt.

**Comment by smile-momoda** [comment]
heheda




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CoderWGB"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 下午4:09
收件人:&nbsp;"smile-momoda/wx"<wx@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[smile-momoda/wx] 呵呵哒 (#1)




rt.

**Comment by WangGuibin** [comment]
@smile-momoda  It's OK 👌

**Comment by smile-momoda** [comment]
what are u nongshane




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CoderWGB"<notifications@github.com&gt;; 
发送时间: 2020年3月4日(星期三) 下午4:24
收件人: "smile-momoda/wx"<wx@noreply.github.com&gt;; 
抄送: "微笑@么么哒！"<1486450630@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [smile-momoda/wx] 呵呵哒 (#1)




@smile-momoda  It's OK

**Comment by WangGuibin** [comment]
> what are u nongshane
> […](#)

What's your mean, I can't got it.

**Comment by smile-momoda** [comment]
what r u弄啥呢？你不懂？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CoderWGB"<notifications@github.com&gt;; 
发送时间: 2020年3月4日(星期三) 下午4:27
收件人: "smile-momoda/wx"<wx@noreply.github.com&gt;; 
抄送: "微笑@么么哒！"<1486450630@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [smile-momoda/wx] 呵呵哒 (#1)



 
what are u nongshane
 …
  
What's your mean, I can't got it.
